CREATE OR REPLACE PROCEDURE WEATHER_DB.FINAL.LOAD_WEATHER_FINAL()
RETURNS VARCHAR
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS '
try {
  var sql_command = `
    CREATE OR REPLACE TABLE FINAL.WEATHER_FINAL AS
    SELECT
      LOCATION,
      DATE_TRUNC(''DAY'', DATE_RECORDED) AS DATE,
      ROUND(AVG(TEMPERATURE), 1) AS AVG_TEMPERATURE,
      ROUND(MIN(TEMPERATURE), 1) AS MIN_TEMPERATURE,
      ROUND(MAX(TEMPERATURE), 1) AS MAX_TEMPERATURE,
      ROUND(AVG(HUMIDITY), 0) AS AVG_HUMIDITY,
      COUNT_IF(WEATHER_CATEGORY = ''RAINY'') AS RAINY_HOURS,
      COUNT_IF(IS_HOT) AS HOT_HOURS
    FROM STAGE.WEATHER_STAGE
    GROUP BY LOCATION, DATE
    ORDER BY LOCATION, DATE;
  `;

  snowflake.execute({sqlText: sql_command});
  return ''FINAL.WEATHER_FINAL table created/updated successfully.'';
} catch(err) {
  return ''Error: '' + err.message;
}
';